# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^dummy_files/.*$
      - id: end-of-file-fixer
        exclude: ^dummy_files/.*$
      - id: check-yaml
        exclude: ^dummy_files/.*$
        #
        # setting --unsafe due to check-yaml incorrectly flagging !Ref tags in Cloudformation
        #
        args:
          - --unsafe
      - id: check-added-large-files
        exclude: ^dummy_files/.*$
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.75.1  # The version of cfn-lint to use
    hooks:
      - id: cfn-lint
        files: (src)/.*\.(yml|yaml)
        exclude: ^dummy_files/.*$
        args: [--non-zero-exit-code, error]
  - repo: https://github.com/AleksaC/mirrors-cfn-nag
    rev: v0.8.9  # Use the sha / tag you want to point at
    hooks:
      - id: cfn-nag
        files: (src)/.*\.(yml|yaml)$  # Set to regex matching filenames of your cloudformation templates
        exclude: ^dummy_files/.*$
        #  args: [--fail-on-warnings, --input-path]
        args: [ --input-path ]
  # for checking python code
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        language: python
        language_version: python3
        types: [python]
        exclude: ^dummy_files/.*$
        args: [ --verbose ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        exclude: ^dummy_files/.*$
        args: [--line-length=100]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^dummy_files/.*$
        args: [--max-line-length=100]
  # for checking shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        exclude: ^dummy_files/.*$
        args:
          - "--severity=error"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.36.0'
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        exclude: ^dummy_files/.*$
        types: [file]
  #
  # Implements file-based, updated-files, and all-files scans using Checkov
  #
  # - repo: ../checkov-precommit-wrapper
  #   rev: '33f654a2946fcb85fa82b734c1684ea128675613'
  - repo: git@github.com:aws-samples/automated-security-helper.git
    rev: 'v2.0.0'
    hooks:
      - id: ash
        files: \.yaml|\.yml|\.json$
        exclude: ^dummy_files/.*|.*/package.json|.*\.eslintrc.json|.*\.pre-commit-config.yaml$
        args: [ --framework, cloudformation, json, yaml, secrets, gitlab_ci, --skip-check, CKV_SECRET_6, -- ]
  #
  # Alwasys runs full directory scans for some reason
  #
  # - repo: https://github.com/antonbabenko/pre-commit-terraform.git
  #   rev: 'v1.77.1'
  #   hooks:
  #     - id: terraform_checkov
  #       files: \.yaml|\.json|\.yml$
  #       args: [ '--args=--framework cloudformation json yaml secrets', '--args=--skip-check CKV_SECRET_6' ]
